{{- $fullname := include "clawcluster.fullname" . -}}
{{- $namespace := include "clawcluster.namespace" . -}}
{{- if and .Values.hiclawManager.secretTemplate.create (not .Values.hiclawManager.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hiclawManager.secretTemplate.name | default (printf "%s-hiclaw-manager" $fullname) }}
  namespace: {{ $namespace }}
  labels:
    {{- include "clawcluster.componentLabels" (dict "ctx" . "component" "hiclaw-manager") | nindent 4 }}
type: {{ .Values.hiclawManager.secretTemplate.type }}
stringData:
  {{- toYaml .Values.hiclawManager.secretTemplate.stringData | nindent 2 }}
{{- end }}
