from __future__ import annotations

import pytest

from models.publish import PublishTarget
from publishers.gitlab import GitLabPublisher


class FakeBranches:
    def __init__(self) -> None:
        self.existing: set[str] = set()
        self.created: list[dict[str, str]] = []

    def get(self, branch_name: str) -> dict[str, str]:
        if branch_name not in self.existing:
            raise RuntimeError("not found")
        return {"name": branch_name}

    def create(self, payload: dict[str, str]) -> dict[str, str]:
        self.existing.add(payload["branch"])
        self.created.append(payload)
        return payload


class FakeCommits:
    def __init__(self) -> None:
        self.created: list[dict[str, object]] = []

    def create(self, payload: dict[str, object]) -> dict[str, str]:
        self.created.append(payload)
        return {
            "id": "abc123def456",
            "short_id": "abc123de",
            "web_url": "https://gitlab.example/project/-/commit/abc123def456",
        }


class FakeMergeRequests:
    def __init__(self) -> None:
        self.created: list[dict[str, object]] = []

    def create(self, payload: dict[str, object]) -> dict[str, object]:
        self.created.append(payload)
        return {
            "iid": 17,
            "web_url": "https://gitlab.example/project/-/merge_requests/17",
        }


class FakeProject:
    def __init__(self) -> None:
        self.id = 999
        self.branches = FakeBranches()
        self.commits = FakeCommits()
        self.mergerequests = FakeMergeRequests()


class FakeProjectsManager:
    def __init__(self, project: FakeProject) -> None:
        self.project = project
        self.requested: list[str] = []

    def get(self, project_id: str) -> FakeProject:
        self.requested.append(project_id)
        return self.project


class FakeGitLabClient:
    def __init__(self, project: FakeProject) -> None:
        self.projects = FakeProjectsManager(project)


@pytest.mark.asyncio
async def test_gitlab_publisher_creates_branch_and_commit(artifact_store_factory, make_publish_request, mocker) -> None:
    artifact_uri = "s3://hiclaw-storage/shared/tasks/task-3/result.md"
    artifact_store = artifact_store_factory({artifact_uri: "Published markdown body"})
    project = FakeProject()
    gitlab_client = FakeGitLabClient(project)
    publisher = GitLabPublisher(artifact_store=artifact_store, gitlab_client=gitlab_client)
    commit_spy = mocker.spy(project.commits, "create")

    publish_request = make_publish_request(
        target=PublishTarget.GITLAB_BRANCH,
        artifact_uris=[artifact_uri],
        metadata={
            "project_id": "999",
            "base_branch": "main",
            "branch_name": "clawcluster/wi_test_publish/task-3",
            "files": [
                {
                    "artifact_uri": artifact_uri,
                    "file_path": "docs/result.md",
                    "action": "create",
                }
            ],
        },
    )
    result = await publisher.publish(publish_request)

    assert gitlab_client.projects.requested == ["999"]
    assert project.branches.created == [{"branch": "clawcluster/wi_test_publish/task-3", "ref": "main"}]
    assert commit_spy.call_count == 1
    assert project.commits.created[0]["branch"] == "clawcluster/wi_test_publish/task-3"
    assert project.commits.created[0]["actions"] == [
        {"action": "create", "file_path": "docs/result.md", "content": "Published markdown body"}
    ]
    assert result.external_refs == {"gitlab_project_id": "999"}
    assert result.artifacts[0].kind == "branch_ref"


@pytest.mark.asyncio
async def test_gitlab_publisher_opens_merge_request(artifact_store_factory, make_publish_request) -> None:
    artifact_uri = "s3://hiclaw-storage/shared/tasks/task-4/workflow.json"
    artifact_store = artifact_store_factory(
        {
            artifact_uri: {
                "actions": [
                    {
                        "file_path": "workflows/approved.json",
                        "action": "update",
                        "content": "{\"approved\": true}",
                    }
                ]
            }
        }
    )
    project = FakeProject()
    gitlab_client = FakeGitLabClient(project)
    publisher = GitLabPublisher(artifact_store=artifact_store, gitlab_client=gitlab_client)

    publish_request = make_publish_request(
        target=PublishTarget.GITLAB_MR,
        artifact_uris=[artifact_uri],
        metadata={
            "project_id": "999",
            "branch_name": "clawcluster/wi_test_publish/task-4",
            "mr_title": "Publish approved workflow",
            "mr_description": "Generated by publisher bridge",
        },
    )
    result = await publisher.publish(publish_request)

    assert project.commits.created[0]["actions"] == [
        {"action": "update", "file_path": "workflows/approved.json", "content": "{\"approved\": true}"}
    ]
    assert project.mergerequests.created == [
        {
            "source_branch": "clawcluster/wi_test_publish/task-4",
            "target_branch": "main",
            "title": "Publish approved workflow",
            "description": "Generated by publisher bridge",
            "remove_source_branch": False,
            "squash": False,
        }
    ]
    assert result.external_refs == {"gitlab_project_id": "999", "gitlab_mr_iid": 17}
    assert result.artifacts[1].kind == "mr_ref"
