upstream policy-bridge-api {
    server policy-bridge:${POLICY_BRIDGE_PORT};
}

server {
    listen 80;
    listen 443 ssl;
    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;
    server_name policy.${DOMAIN};

    client_max_body_size 64m;

    location /api/policy/ {
        proxy_pass http://policy-bridge-api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
    }
}
